### ISSUE TITLE
Log outputs

### ISSUE THREAD

**Issue by mmagician** [StefanosChaliasos/zkrollup-benchmarking#4]
Currently, the raw logs aren't saved anywhere (AFAICS), despite the [comment](https://github.com/StefanosChaliasos/zkrollup-benchmarking/blob/268ea0a039ab1973151ccd2bacd855a775410c23/POLYGON-INSTRUCTIONS.md#L179):
> This process will take a while to finish, and it will start outputing a lot of logs from the prover (that later we will save as `logs`).

Am I missing something? If not, it would be good to pipe them to a separate file for later inspection.

**Comment by StefanosChaliasos** [comment]
Yeah, we probably forgot to add the `tee` command in the instruction
